// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// This is the core AATKit package. It ships AATKit and nothing else — every ad
// network and CMP lives in its own AATKit-<Network> package, so integrators only
// pull in the third-party SDKs they actually use.
//
// The binary targets below are generated by BuildScripts/SPM_scripts/BinariesGenerator
// in the AATKit repository; everything after the marker is rewritten on release.

import PackageDescription

let package = Package(
    name: "AATKit",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-Core", targets: ["AATKit-Core"]),
    ],
    // Mark: Targets
    targets: [
        // AATKit target
        .target(name: "AATKit-Core",
                dependencies: ["AATKit"],
                path: "./Sources/AATKit"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATKit",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta1/AATKit.zip",
            checksum: "11c31328dfb3d35fa26e537b116b6671ff43e17a7cce30aa93245e7b853b1209"
        ),
    ]
)
